In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data=pd.read_csv("iris.csv")

In [3]:
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
data=data.drop(["Id"],axis=1)

In [5]:
data.isna().sum()

SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [6]:
x=data.loc[:,data.columns!="Species"].values
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
species={"Iris-setosa":0,"Iris-versicolor":1,"Iris-virginica":3}

In [8]:
y=data["Species"].replace(species).values

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
trainx,testx,trainy,testy=train_test_split(x,y,test_size=0.20)

In [11]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classifier.fit(trainx,trainy)

KNeighborsClassifier()

In [12]:
classifier.predict(testx)

array([1, 0, 3, 1, 1, 1, 3, 3, 3, 1, 0, 3, 3, 0, 0, 3, 0, 1, 1, 0, 1, 1,
       3, 0, 3, 1, 0, 0, 1, 0], dtype=int64)

In [13]:
testy

array([1, 0, 3, 1, 1, 1, 3, 3, 3, 3, 0, 3, 3, 0, 0, 3, 0, 1, 1, 0, 1, 1,
       3, 0, 3, 1, 0, 0, 1, 0], dtype=int64)

In [14]:
classifier.score(testx,testy)*100

96.66666666666667

In [15]:
input=np.array([6.3, 3.4, 5.6, 2.4]).reshape(1,-1)
classifier.predict(input)

array([3], dtype=int64)

In [16]:
import pickle as pkl


In [18]:
with open('model.pkl','wb') as f:
    pkl.dump(classifier,f)